const char* authors=
"BpmDj: Free Dj Tools\n"
"Copyright (C) 2001-2011 Werner Van Belle\n"
"========================================\n"
"\n"
"Active\n"
"------\n"
"Werner Van Belle <werner@yellowcouch.org>\n"
"  Created the project\n"
"Bernard Fortz <bernard.fortz@gmail.com>\n"
"  JACK support, Midi bindings, Gentoo packaging, External clock\n"
"\n"
"Passive\n"
"-------\n"
"Toni Graffy <oc2pus@arcor.de>\n"
"  Suse packaging\n"
"F. Murtagh <murtagh@scivax.stsci.edu>\n"
"  PCA-code\n"
"Julius O. Smith <http://www-ccrma.stanford.edu/~jos/>\n"
"  Low pass filter\n"
"Detlef: \n"
"  64 bit support\n"
"Bruce Perens <bruce@pixar.com>\n"
"  Electrif Fence\n"
"Tom Vogt <tom@lemuria.org>\n"
"  Import filter\n"
"James Gerken <phlegm@mib.org>\n"
"  Some minor patches       \n"
"Majc_ <majci888@gmail.com>\n"
"  Slackware packaging\n"
"Pierre Marc Dumuid <pierre.dumuid@adelaide.edu.au>\n"
"  fedora defines\n"
"Mic Tamere <oinike@hotmail.fr>\n"
"  ubuntu defines 64 bit\n"
"bloody.middlefinger@yellowcouch.org\n"
"  Defines for opensuse10.3\n"
"Philippe Schelte <dubphil@free.fr>\n"
"  Defines for gentoo\n"
"Stefan Wanje\n"
"  Defines for fedora14\n"
"Martin Stolpe <martin.stople@uni-ulm.de>\n"
"  Cmake files\n"
"  \n"
"Donations\n"
"---------\n"
"Sam Liddicott\n"
"Camille d'Alméras\n"
;
