#!/bin/bash
device="/dev/dsp"
fullname=$1;

if [ $1 = "-d" ]; then
  device=$2;
  fullname=$3;
  fi

rawname=`basename $fullname`.raw

! (test -f $rawname) && ./glue-mp3raw $fullname &
./cbpm-player -v -d $device -n `./glue-getperiod $fullname` $rawname
