#!/bin/bash
! (test -f `basename $1`.raw) && ./glue-bpmraw $1 2>/dev/null >/dev/null;
echo -n `basename $1` " "
./glue-bpmgraph `basename $1`.raw
grep TEMPO `basename $1 .mp3`.idx
rm `basename $1`.raw
