#!/bin/bash
# this small script fixes all the link targets if they require updating
# conflicts will be reported and stopped
if ls *.L >/dev/null 2>/dev/null; then 
  for a in *.L; do 
    link=$a
    target=`echo $a | sed 's/\.L$//'`
    # if the target already exists without a copy file then we 
    # report a possible unwanted overwrite
    if test -e $target -a ! -e .$target; then
	echo "About to overwrite "$target;
	exit 1;
    fi
    # if the target didn't exist we creat it
    if test ! -e .$target -a ! -e $target; then 
	echo " [copy] "$target
	cp -f $link $target;
	cp -f $link .$target; 
    fi
    # if the target exists and are the same
    if test -e .$target -a -e $target; then 
	if cmp -s $target .$target; then 
	    if cmp -s $link $target; then
		echo -n ; # they were already the same
	    else
		echo " [copy] "$target
		cp -f $link $target; 
		cp -f $link .$target; 
	    fi
	else
        # if the previous and the current version do not match
        # we must assume some CVS related conflict
	    echo $target " was modified without updating the "$link " file."; 
	    exit 1; 
	fi
    fi
  done
fi

exit 0
